#pragma once

#include "NativeGameplayTags.h"

namespace CYGameplayTags
{
	// Native Input Tags
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);

	// Item Input Tags
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interact);
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack);

	// Inventory Slot Input Tags (1~9)
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UseSlot1);
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UseSlot2);
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UseSlot3);
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UseSlot4);
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UseSlot5);
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UseSlot6);
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UseSlot7);
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UseSlot8);
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UseSlot9);
	
	// Ability Input Tags
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability_Jump);
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability_WeaponAttack);
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability_PlaceTrap);
	
}