#pragma once

#include "NativeGameplayTags.h"

namespace CYGameplayTags
{
	// 아이템 관련 입력 태그들
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interact);
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack);
	
	// 인벤토리 슬롯 입력
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UseSlot1);
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UseSlot2);
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UseSlot3);
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UseSlot4);
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UseSlot5);
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UseSlot6);

	// 어빌리티 입력 태그들
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability_WeaponAttack);
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability_PlaceTrap);
}