#pragma once

#include "NativeGameplayTags.h"

namespace CYGameplayTags
{
	// Combat Ability Tags
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Combat_WeaponAttack);
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Combat_PlaceTrap);

	// Item Tags
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Base);
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Weapon);
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Trap);
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Consumable);

	// State Tags
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Attacking);
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Stunned);
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Dead);

	// Cooldown Tags
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Combat_WeaponAttack);
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Combat_TrapPlace);

	// Event Tags
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Item_Use);

	// Data Tags
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Combat_Damage);
}