#pragma once

#include "NativeGameplayTags.h"

namespace CYGameplayTags
{
	// Combat Ability Tags
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Combat_WeaponAttack);
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Combat_PlaceTrap);

	// State Tags
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Attacking);
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Stunned);
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Dead);

	// Cooldown Tags
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Combat_WeaponAttack);
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Combat_TrapPlace);

	// Effect Tags
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Debuff_Slow);
	CATCHMEIFYOUCAN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Debuff_Freeze);
}